<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Owlip.Shared.Authentication</PackageId>
    <Version>0.1.1</Version>
    <Authors>owlillp</Authors>
    <Company>owlillp</Company>
    <PackageDescription>Core</PackageDescription>
    <RepositoryUrl>https://github.com/owlillp/Shared</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Shared.SharedKernel\Shared.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
