<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Owlip.Shared.Framework</PackageId>
    <Version>0.0.1</Version>
    <Authors>owlillp</Authors>
    <Company>owlillp</Company>
    <PackageDescription>Framework</PackageDescription>
    <RepositoryUrl>https://github.com/owlillp/Shared</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.SharedKernel\Shared.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Sinks.Seq" />
  </ItemGroup>

</Project>
