<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Owlip.Shared.Core</PackageId>
    <Version>0.0.1</Version>
    <Authors>owlillp</Authors>
    <Company>owlillp</Company>
    <PackageDescription>Core</PackageDescription>
    <RepositoryUrl>https://github.com/owlillp/Shared</RepositoryUrl>
  </PropertyGroup>

</Project>
